config/routes.rb
Rails.application.routes.draw do
  root 'importer#index'

  get 'importer/index'
  get '/products' => 'products#index', as: :products
  get '/products/edit/:id' => 'products#edit', as: :edit_product
  get '/products/show/:id' => 'products#show', as: :show_product

  post '/products/update/:id' => 'products#update', as: :update_product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assortment.rb
class Assortment < ApplicationRecord
  self.table_name = "assortment"

  belongs_to :product
  belongs_to :shop
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  has_many :attribute_translations
  has_many :attribute_values, foreign_key: "attribute_value_id", class_name: "AttributeValue"
  has_many :attribute_value_transformations
  has_many :product_attribute_values

  def is_editable
    true
  end

  def information
    name = self.attribute_translations.first.name
    if self.suffix && self.suffix != ''
      return '#' + self.id.to_s + ' ' + name + ', ' + self.suffix
    end

    '#' + self.id.to_s + ' ' + name
  end
end

app/models/attribute_value.rb
class AttributeValue < ApplicationRecord
  belongs_to :att, class_name: 'Attribute', foreign_key: "attribute_id"

  has_many :product_attribute_values
  has_many :attribute_value_translations

  def attribute
    Attribute.find(self.attribute_id)
  end
end

app/models/categories_map.rb
class CategoriesMap < ApplicationRecord
  self.table_name = "categories_map"

  belongs_to :seller_category, class_name: 'Category', foreign_key: "seller_category_id"
  belongs_to :supplier_category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_map
  has_many :category_closure
  has_many :product_categories
  has_many :products, through: :product_categories
  has_many :supplier_categories, through: :categories_map

  # Not full. Used for testing.
  def full_path_name(separator)
    if self.parent_id
      parent = Category.find(self.parent_id)
      return self.name + separator + parent.name
    end

    self.name
  end
end

app/models/category_closure.rb
class CategoryClosure < ApplicationRecord
  self.table_name = "category_closure"

  belongs_to :ancestor, class_name: 'Category', foreign_key: "ancestor"
  belongs_to :descendant, class_name: 'Category', foreign_key: "descendant"
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 50

  belongs_to :family, class_name: 'ProductFamily', foreign_key: "family_id", optional: true
  belongs_to :default_variation, class_name: 'Variation', foreign_key: "default_variation_id", optional: true

  has_many :product_attribute_values
  has_many :product_links
  has_many :assortment
  has_many :variations
  has_many :product_categories
  has_many :categories, through: :product_categories

  def has_description
    self.product_attribute_values.each do |pav|
      if pav.att.special_type === 'description'
        return true
      end
    end

    false
  end

  def description
    self.product_attribute_values.each do |pav|
      if pav.att.special_type === 'description'
        return pav.attribute_value.attribute_value_translations.first.attr_value
      end
    end

    ''
  end

  def supplier_categories
    {}
  end

  def get_why_not_active
    'Because'
  end

  def attribute_values
    av = []
    self.product_attribute_values.each do |pav|
      av << AttributeValue.find(pav.attribute_value.id)
    end
    av
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_family.rb
class ProductFamily < ApplicationRecord
  has_many :product_family_attribute_groups
  has_many :products
end

app/models/product_link.rb
class ProductLink < ApplicationRecord
  belongs_to :product
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :assortment
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :supplier_attributes
  has_many :supplier_items
  has_many :variation_gtins
end

app/models/supplier_attribute.rb
class SupplierAttribute < ApplicationRecord
  belongs_to :supplier
  belongs_to :att, class_name: 'Attribute', foreign_key: "attribute_id"

  has_many :supplier_attribute_translations
  has_many :supplier_item_attribute_values
end

app/models/supplier_category.rb
class SupplierCategory < ApplicationRecord
  belongs_to :supplier

  has_many :categories, through: :categories_map
end

app/models/supplier_item.rb
class SupplierItem < ApplicationRecord
  belongs_to :supplier_category
  belongs_to :supplier
  belongs_to :variation

  has_many :supplier_item_attribute_values
end

app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :product

  has_many :variation_gtins
  has_many :variation_photos

  has_one :supplier_item
end

app/models/variation_gtin.rb
class VariationGtin < ApplicationRecord
  belongs_to :variation
  belongs_to :supplier
end

app/models/variation_photo.rb
class VariationPhoto < ApplicationRecord
  belongs_to :variation
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.includes(
        :assortment,
        :product_attribute_values,
        variations: [:variation_gtins, :variation_photos]
    ).page params[:page]
    @shops = Shop.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @families = ProductFamily.all
  end

  def update
    @family = ProductFamily.find(product_params[:family_id])
    @product = Product.includes(
        :assortment,
        :product_attribute_values,
        variations: [:variation_photos]
    ).find(params[:id])

    if @product.update(product_params)
      redirect_to(:action => 'index')
    else
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:family_id)
  end
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/progress_bar.rb
class ProgressBar

  def initialize(total)
    @total   = total
    @counter = 1
  end

  def increment
    complete = sprintf("%#.2f%", ((@counter.to_f / @total.to_f) * 100))
    print "\r\e[0K#{@counter}/#{@total} (#{complete})"
    @counter += 1
  end

end

app/views/products/_additional_info.html.haml
.card.mb-3
  .card-header
    %h6= t('additional_info')
  .card-block
    %table.table.table-responsive
      %tbody
        %tr
          %th= t('uuid')
          %td= @product.uuid
        %tr
          %th= t('status')
          %td
            =render 'product_activeness'
        - if @product.family
          %tr
            %th= t('family')
            %td= @product.family.name
        %tr
          %th= t('created_at')
          %td= @product.created_at

app/views/products/_attributes.html.haml
.card
  .card-header
    %h6= t('attributes')
  .card-block.container
    %table.table.table-responsive
      %tbody>
        - @product.attribute_values.each do |attribute_value|
          - if attribute_value.attribute.is_editable
            %tr.row
              %th.col-4
                -if attribute_value.attribute.attribute_translations.any?
                  %span.light-grey= attribute_value.attribute.information
              %td.col-8= attribute_value.attribute_value_translations.first.attr_value

app/views/products/_categories.html.haml
.card.mb-3
  .card-header
    %h4= t('categories')
  .card-block
    %ul.list-unstyled
      - @product.categories.each do |category|
        %li.p-3= category.full_path_name('/ ')

app/views/products/_links.html.haml
.card.mt-3
  .card-header
    %h6= t('links')
  .card-block.container
    - if @product.product_links.any?
      %table.table.table-responsive
        %thead
          %tr.row
            %th.col-3= t('title')
            %th.col-5= t('url')
            %th.col-2= t('type')
            %th.col-2= t('status')
        %tbody
          - @product.product_links.each do |link|
            %tr.row
              %td.col-3= link.title
              %td.col-5
                %a{href: link.url, 'target': '_blank'}= link.url
              %td.col-2= link.link_type
              %td.col-2
                - if link.is_active
                  %span.badge.badge-success= t('active')
                - else
                  %span.badge.badge-danger= t('inactive')
    - else
      %p.text-warning= t('product_has_no_links')

app/views/products/_notes.html.haml
- if @product.note
  .card
    .card-header
      %h6= t('notes')
    .card-block
      %p.p-3= @product.note

app/views/products/_photos.html.haml
.container
  .row.mt-4.mb-4
    - @product.default_variation.variation_photos.each do |photo|
      - res = Net::HTTP.get_response(URI.parse(photo.file))
      - if res.code.to_i >= 200 && res.code.to_i < 400
        .col-md-3
          =render 'photo_action_buttons'
          %a{href: photo.file, 'data-toggle': 'imagebox'}
            %img.img-thumbnail{src: photo.file}
            %a.wordwrap{href: photo.file}= File.basename photo.file
            %br
            - if photo.supplier_priority
              = "SPC priority: #{ photo.supplier_priority }"
            .photos-additional-info
              - if photo.size or (photo.width and photo.height)
                = 'Size:'
                - if photo.width and photo.height
                  = "#{ photo.width }x#{ photo.height }#{ photo.size ? ',' : '' }"
                - if photo.size
                  = photo.size
                %br
              - if photo.source
                = "Source: #{ photo.source }"
                %br

app/views/products/_product_activeness.html.haml
%ul.list-unstyled
  - if @product.assortment.any?
    - @product.assortment.each do |assortment_item|
      - if assortment_item.is_active
        %li.text-nowrap
          %span.badge.badge-success= "#{assortment_item.shop.name}: active"
      - else
        %li.text-nowrap{'data-toggle': 'tooltip', 'data-placement': 'auto left', 'data-container': 'body', 'title': @product.get_why_not_active(assortment_item.shop)}
          %span.badge.badge-warning= "#{assortment_item.shop.name}: hidden"
          %i.fa.fa-info-circle

app/views/products/_sidebar.html.haml
- if @product.default_variation.variation_gtins.any?
  .card.mb-3
    .card-header
      %h6= t('gtins')
    %ul.pt-3
      - @product.default_variation.variation_gtins.each do |gtin|
        %li= gtin.value

- if @product.variations.any?
  =render 'additional_info'

- if @product.categories.any?
  =render 'categories'

-  if @product.supplier_categories.any?
  =render 'supplier_categories'

- main_photo = @product.default_variation.variation_photos.first
- if main_photo
  .card.mb-3
    .card-header
      %h6= t('photo')
    .card-block
      %a{href: main_photo.file, 'data-toggle': 'imagebox'}
        %img.img-thumbnail{src: main_photo.file}

=render 'notes'

app/views/products/edit.html.haml
.container
  %h3= t('edit_product')
  %br
  = form_for @product, url: update_product_path(@product), method: :post do |f|
    - if @product.errors.any?
      #error_explanation
        %ul
          - @product.errors.full_messages.each do |msg|
            %li.text-red= msg

    .form-group.row.m-0
      = f.label t('family'), {class: 'col-2 col-form-label'}
      = f.select(:family_id, @families.collect {|family| [family.name, family.id]}, {}, {class: 'form-control col-10'})

    -#- @product.product_attribute_values.each do |pav|
    -#  .form-group.row.m-0
    -#    = f.label pav.attribute_id, {class: 'col-2 col-form-label'}
    -#    = f.select(:value_id, pav.attribute_value.collect {|family| [family.name, family.id]}, {}, {class: 'form-control col-10'})

    -#.form-group.row.m-0
    -#  = f.label t('upload_photo'), {class: 'col-2 col-form-label'}
    -#  = f.file_field(:attachments, {multiple: true, direct_upload: true, class: 'form-control col-10'})

    %br
    %button.btn.btn-primary{type: 'submit'}= t('save')

app/views/products/index.html.haml
.container
  %h3= t('products')
  %br
  %table.table.table-bordered.table-responsive
    %thead
      %tr.row.m-0
        %th.col-1= t('id')
        %th.col-1= t('photo')
        %th.col-5= t('title')
        %th.col-2= t('ean')
        %th.col-2= t('status')
        %th.col-1= t('actions')
    %tbody
      - @products.each do |product|
        %tr.row.m-0
          %td.col-1= product.id
          %td.col-1
            - if product.variations.first.variation_photos.any?
              %img.img-thumbnail{src: product.variations.first.variation_photos.first.file}
          %td.col-5
            - product.product_attribute_values.each do |pav|
              - if pav.att.special_type === 'title'
                - pav.attribute_value.attribute_value_translations.each do |translation|
                  %em= "[#{translation.locale}]:"
                  %span= translation.attr_value
          %td.col-2
            - if product.variations.first.variation_gtins.any?
              - product.variations.first.variation_gtins.each do |gtin|
                = gtin.value
          %td.col-2
            =render 'product_activeness', :@product => product
          %td.col-1
            %a.btn.btn-outline-primary.btn-sm.pull-right{href: edit_product_path(product.id)}= icon('pencil')
            %a.btn.btn-outline-primary.btn-sm.pull-right.mr-1{href: show_product_path(product.id)}= icon('search-plus')
      = paginate @products

app/views/products/show.html.haml
.container
  %h3= t('show_product')
  %br
  .row
    .col-md-9
      .card
        .tabpanel.p-3
          %ul#productTabs.nav.nav-tabs.nav-justified
            %li.nav-item{role: 'presentation'}
              %a#information-tab.nav-link.active{href: '#information', 'aria-controls': 'seo', role: 'tab', 'data-toggle': 'tab'}
                %h6= t('information')
            %li.nav-item{role: 'presentation'}
              %a#change-log-tab.nav-link{href: '#change_log', 'aria-controls': 'change-logs', role: 'tab', 'data-toggle': 'tab'}
                %h6= t('change_log')
            %li.nav-item{role: 'presentation'}
              %a#supplier-info-tab.nav-link{href: '#supplier_info', 'data-id': 'supplier-info-tab', 'data-product-id': @product.id, 'aria-controls': 'seo', role: 'tab', 'data-toggle': 'tab'}
                %h6= t('supplier_info')
          #productTabsContent.tab-content.mt-3
            #information.tab-pane.fade.show.active{role: 'tabpanel', 'aria-labelledby': 'information-tab'}
              .row
                .col-md-12
                  .card
                    .card-header
                      %h6= t('description')
                    .card-block
                      - if @product.has_description
                        %p.p-3= @product.description.html_safe
                      - else
                        %p.p-3.text-warning= t('no_description_warning')
              .row.mt-3
                .col-md-12
                  .card
                    .card-header
                      %h6= t('photos')
                    .card-block
                      =render 'photos'
              .row.mt-3
                .col-md-12
                  =render 'attributes'
              - if @product.product_links.any?
                =render 'links'
            #change_log.tab-pane.fade{role: 'tabpanel', 'aria-labelledby': 'change-log-tab'}
              =render 'change_log'
            #supplier_info.tab-pane.fade{role: 'tabpanel', 'aria-labelledby': 'supplier-info-tab'}
              =render 'supplier_info_tab'
    .col-md-3
      =render 'sidebar'